/** Curated destination catalog, seeded into the destinations table on startup.
 *  tier 1 = scan often (perennial favorites), 2 = normal, 3 = long-tail. */

export interface CatalogEntry {
  iata: string;
  city: string;
  country: string;
  region: 'domestic' | 'americas' | 'europe' | 'asia' | 'africa' | 'oceania';
  tier: 1 | 2 | 3;
}

export const DESTINATION_CATALOG: CatalogEntry[] = [
  // --- Tier 1: perennial favorites ---
  { iata: 'CUN', city: 'Cancún', country: 'Mexico', region: 'americas', tier: 1 },
  { iata: 'MEX', city: 'Mexico City', country: 'Mexico', region: 'americas', tier: 1 },
  { iata: 'SJD', city: 'Cabo San Lucas', country: 'Mexico', region: 'americas', tier: 1 },
  { iata: 'HNL', city: 'Honolulu', country: 'United States', region: 'domestic', tier: 1 },
  { iata: 'OGG', city: 'Maui', country: 'United States', region: 'domestic', tier: 1 },
  { iata: 'NYC', city: 'New York', country: 'United States', region: 'domestic', tier: 1 },
  { iata: 'MIA', city: 'Miami', country: 'United States', region: 'domestic', tier: 1 },
  { iata: 'SEA', city: 'Seattle', country: 'United States', region: 'domestic', tier: 1 },
  { iata: 'SJU', city: 'San Juan', country: 'Puerto Rico', region: 'americas', tier: 1 },
  { iata: 'LON', city: 'London', country: 'United Kingdom', region: 'europe', tier: 1 },
  { iata: 'PAR', city: 'Paris', country: 'France', region: 'europe', tier: 1 },
  { iata: 'ROM', city: 'Rome', country: 'Italy', region: 'europe', tier: 1 },
  { iata: 'BCN', city: 'Barcelona', country: 'Spain', region: 'europe', tier: 1 },
  { iata: 'MAD', city: 'Madrid', country: 'Spain', region: 'europe', tier: 1 },
  { iata: 'LIS', city: 'Lisbon', country: 'Portugal', region: 'europe', tier: 1 },
  { iata: 'AMS', city: 'Amsterdam', country: 'Netherlands', region: 'europe', tier: 1 },
  { iata: 'DUB', city: 'Dublin', country: 'Ireland', region: 'europe', tier: 1 },
  { iata: 'TYO', city: 'Tokyo', country: 'Japan', region: 'asia', tier: 1 },
  { iata: 'OSA', city: 'Osaka', country: 'Japan', region: 'asia', tier: 1 },
  { iata: 'SEL', city: 'Seoul', country: 'South Korea', region: 'asia', tier: 1 },

  // --- Tier 2: broad coverage ---
  { iata: 'YVR', city: 'Vancouver', country: 'Canada', region: 'americas', tier: 2 },
  { iata: 'YYZ', city: 'Toronto', country: 'Canada', region: 'americas', tier: 2 },
  // Jalisco is state-level 3, but the advisory places no restrictions on
  // Puerto Vallarta or the Guadalajara metro — kept per user's call.
  { iata: 'PVR', city: 'Puerto Vallarta', country: 'Mexico', region: 'americas', tier: 2 },
  { iata: 'GDL', city: 'Guadalajara', country: 'Mexico', region: 'americas', tier: 2 },
  { iata: 'SJO', city: 'San José', country: 'Costa Rica', region: 'americas', tier: 2 },
  { iata: 'LIR', city: 'Liberia', country: 'Costa Rica', region: 'americas', tier: 2 },
  { iata: 'PTY', city: 'Panama City', country: 'Panama', region: 'americas', tier: 2 },
  { iata: 'LIM', city: 'Lima', country: 'Peru', region: 'americas', tier: 2 },
  { iata: 'CUZ', city: 'Cusco', country: 'Peru', region: 'americas', tier: 2 },
  { iata: 'EZE', city: 'Buenos Aires', country: 'Argentina', region: 'americas', tier: 2 },
  { iata: 'SCL', city: 'Santiago', country: 'Chile', region: 'americas', tier: 2 },
  { iata: 'RIO', city: 'Rio de Janeiro', country: 'Brazil', region: 'americas', tier: 2 },
  { iata: 'ANC', city: 'Anchorage', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'BOS', city: 'Boston', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'NAS', city: 'Nassau', country: 'Bahamas', region: 'americas', tier: 2 },
  { iata: 'MBJ', city: 'Montego Bay', country: 'Jamaica', region: 'americas', tier: 2 },
  { iata: 'AUA', city: 'Aruba', country: 'Aruba', region: 'americas', tier: 2 },
  { iata: 'EDI', city: 'Edinburgh', country: 'United Kingdom', region: 'europe', tier: 2 },
  { iata: 'REK', city: 'Reykjavík', country: 'Iceland', region: 'europe', tier: 2 },
  { iata: 'CPH', city: 'Copenhagen', country: 'Denmark', region: 'europe', tier: 2 },
  { iata: 'STO', city: 'Stockholm', country: 'Sweden', region: 'europe', tier: 2 },
  { iata: 'OSL', city: 'Oslo', country: 'Norway', region: 'europe', tier: 2 },
  { iata: 'BER', city: 'Berlin', country: 'Germany', region: 'europe', tier: 2 },
  { iata: 'MUC', city: 'Munich', country: 'Germany', region: 'europe', tier: 2 },
  { iata: 'FRA', city: 'Frankfurt', country: 'Germany', region: 'europe', tier: 2 },
  { iata: 'ZRH', city: 'Zurich', country: 'Switzerland', region: 'europe', tier: 2 },
  { iata: 'VIE', city: 'Vienna', country: 'Austria', region: 'europe', tier: 2 },
  { iata: 'PRG', city: 'Prague', country: 'Czechia', region: 'europe', tier: 2 },
  { iata: 'BUD', city: 'Budapest', country: 'Hungary', region: 'europe', tier: 2 },
  { iata: 'KRK', city: 'Kraków', country: 'Poland', region: 'europe', tier: 2 },
  { iata: 'MIL', city: 'Milan', country: 'Italy', region: 'europe', tier: 2 },
  { iata: 'VCE', city: 'Venice', country: 'Italy', region: 'europe', tier: 2 },
  { iata: 'NAP', city: 'Naples', country: 'Italy', region: 'europe', tier: 2 },
  { iata: 'ATH', city: 'Athens', country: 'Greece', region: 'europe', tier: 2 },
  { iata: 'IST', city: 'Istanbul', country: 'Turkey', region: 'europe', tier: 2 },
  { iata: 'AGP', city: 'Málaga', country: 'Spain', region: 'europe', tier: 2 },
  { iata: 'OPO', city: 'Porto', country: 'Portugal', region: 'europe', tier: 2 },
  { iata: 'BKK', city: 'Bangkok', country: 'Thailand', region: 'asia', tier: 2 },
  { iata: 'HKT', city: 'Phuket', country: 'Thailand', region: 'asia', tier: 2 },
  { iata: 'SGN', city: 'Ho Chi Minh City', country: 'Vietnam', region: 'asia', tier: 2 },
  { iata: 'HAN', city: 'Hanoi', country: 'Vietnam', region: 'asia', tier: 2 },
  { iata: 'SIN', city: 'Singapore', country: 'Singapore', region: 'asia', tier: 2 },
  { iata: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia', region: 'asia', tier: 2 },
  { iata: 'DPS', city: 'Bali', country: 'Indonesia', region: 'asia', tier: 2 },
  { iata: 'MNL', city: 'Manila', country: 'Philippines', region: 'asia', tier: 2 },
  { iata: 'TPE', city: 'Taipei', country: 'Taiwan', region: 'asia', tier: 2 },
  { iata: 'HKG', city: 'Hong Kong', country: 'Hong Kong', region: 'asia', tier: 2 },
  { iata: 'PUJ', city: 'Punta Cana', country: 'Dominican Republic', region: 'americas', tier: 2 },
  { iata: 'OAX', city: 'Oaxaca', country: 'Mexico', region: 'americas', tier: 2 },
  { iata: 'YUL', city: 'Montreal', country: 'Canada', region: 'americas', tier: 2 },
  { iata: 'LIH', city: 'Kauai', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'KOA', city: 'Kona', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'MSY', city: 'New Orleans', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'SFO', city: 'San Francisco', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'DBV', city: 'Dubrovnik', country: 'Croatia', region: 'europe', tier: 2 },
  { iata: 'PDL', city: 'Ponta Delgada', country: 'Portugal', region: 'europe', tier: 2 },
  { iata: 'MCO', city: 'Orlando', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'CHI', city: 'Chicago', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'WAS', city: 'Washington DC', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'SAN', city: 'San Diego', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'LAS', city: 'Las Vegas', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'PDX', city: 'Portland', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'AUS', city: 'Austin', country: 'United States', region: 'domestic', tier: 2 },
  { iata: 'SDQ', city: 'Santo Domingo', country: 'Dominican Republic', region: 'americas', tier: 2 },
  { iata: 'TQO', city: 'Tulum', country: 'Mexico', region: 'americas', tier: 2 },
  { iata: 'SAO', city: 'São Paulo', country: 'Brazil', region: 'americas', tier: 2 },
  { iata: 'NCE', city: 'Nice', country: 'France', region: 'europe', tier: 2 },
  { iata: 'JTR', city: 'Santorini', country: 'Greece', region: 'europe', tier: 2 },
  { iata: 'CNX', city: 'Chiang Mai', country: 'Thailand', region: 'asia', tier: 2 },
  { iata: 'BNE', city: 'Brisbane', country: 'Australia', region: 'oceania', tier: 2 },

  // --- Tier 3: long-tail ---
  { iata: 'FAI', city: 'Fairbanks', country: 'United States', region: 'domestic', tier: 3 },
  { iata: 'YXY', city: 'Whitehorse', country: 'Canada', region: 'americas', tier: 3 },
  { iata: 'UIO', city: 'Quito', country: 'Ecuador', region: 'americas', tier: 3 },
  { iata: 'GPS', city: 'Galápagos', country: 'Ecuador', region: 'americas', tier: 3 },
  { iata: 'DEL', city: 'Delhi', country: 'India', region: 'asia', tier: 3 },
  { iata: 'BOM', city: 'Mumbai', country: 'India', region: 'asia', tier: 3 },
  { iata: 'HYD', city: 'Hyderabad', country: 'India', region: 'asia', tier: 3 },
  { iata: 'CMB', city: 'Colombo', country: 'Sri Lanka', region: 'asia', tier: 3 },
  { iata: 'KTM', city: 'Kathmandu', country: 'Nepal', region: 'asia', tier: 3 },
  { iata: 'CAI', city: 'Cairo', country: 'Egypt', region: 'africa', tier: 3 },
  { iata: 'RAK', city: 'Marrakesh', country: 'Morocco', region: 'africa', tier: 3 },
  { iata: 'CPT', city: 'Cape Town', country: 'South Africa', region: 'africa', tier: 3 },
  { iata: 'JNB', city: 'Johannesburg', country: 'South Africa', region: 'africa', tier: 3 },
  { iata: 'NBO', city: 'Nairobi', country: 'Kenya', region: 'africa', tier: 3 },
  { iata: 'SYD', city: 'Sydney', country: 'Australia', region: 'oceania', tier: 3 },
  { iata: 'MEL', city: 'Melbourne', country: 'Australia', region: 'oceania', tier: 3 },
  { iata: 'AKL', city: 'Auckland', country: 'New Zealand', region: 'oceania', tier: 3 },
  { iata: 'PPT', city: 'Papeete', country: 'French Polynesia', region: 'oceania', tier: 3 },
  { iata: 'NAN', city: 'Nadi', country: 'Fiji', region: 'oceania', tier: 3 },
  { iata: 'SPU', city: 'Split', country: 'Croatia', region: 'europe', tier: 3 },
  { iata: 'CTA', city: 'Catania', country: 'Italy', region: 'europe', tier: 3 },
  { iata: 'PMO', city: 'Palermo', country: 'Italy', region: 'europe', tier: 3 },
  { iata: 'TFS', city: 'Tenerife', country: 'Spain', region: 'europe', tier: 3 },
  { iata: 'FNC', city: 'Madeira', country: 'Portugal', region: 'europe', tier: 3 },
  { iata: 'PVG', city: 'Shanghai', country: 'China', region: 'asia', tier: 3 },
  { iata: 'PEK', city: 'Beijing', country: 'China', region: 'asia', tier: 3 },
  { iata: 'MLE', city: 'Malé', country: 'Maldives', region: 'asia', tier: 3 },
  { iata: 'LVI', city: 'Victoria Falls', country: 'Zambia', region: 'africa', tier: 3 },
  { iata: 'ZQN', city: 'Queenstown', country: 'New Zealand', region: 'oceania', tier: 3 },
  { iata: 'CNS', city: 'Cairns', country: 'Australia', region: 'oceania', tier: 3 },
  { iata: 'SXM', city: 'St. Maarten', country: 'Sint Maarten', region: 'americas', tier: 3 },
  { iata: 'BGI', city: 'Barbados', country: 'Barbados', region: 'americas', tier: 3 },
  { iata: 'CUR', city: 'Curaçao', country: 'Curaçao', region: 'americas', tier: 3 },
  { iata: 'GCM', city: 'Grand Cayman', country: 'Cayman Islands', region: 'americas', tier: 3 },
  { iata: 'PLS', city: 'Turks & Caicos', country: 'Turks and Caicos', region: 'americas', tier: 3 },
  { iata: 'BDA', city: 'Bermuda', country: 'Bermuda', region: 'americas', tier: 3 },
  { iata: 'MID', city: 'Mérida', country: 'Mexico', region: 'americas', tier: 3 },
  { iata: 'MVD', city: 'Montevideo', country: 'Uruguay', region: 'americas', tier: 3 },
  { iata: 'BRU', city: 'Brussels', country: 'Belgium', region: 'europe', tier: 3 },
  { iata: 'HEL', city: 'Helsinki', country: 'Finland', region: 'europe', tier: 3 },
  { iata: 'WAW', city: 'Warsaw', country: 'Poland', region: 'europe', tier: 3 },
  { iata: 'MLA', city: 'Malta', country: 'Malta', region: 'europe', tier: 3 },
  { iata: 'SVQ', city: 'Seville', country: 'Spain', region: 'europe', tier: 3 },
  { iata: 'FLR', city: 'Florence', country: 'Italy', region: 'europe', tier: 3 },
  { iata: 'DAD', city: 'Da Nang', country: 'Vietnam', region: 'asia', tier: 3 },
  { iata: 'CGK', city: 'Jakarta', country: 'Indonesia', region: 'asia', tier: 3 },
  { iata: 'CTS', city: 'Sapporo', country: 'Japan', region: 'asia', tier: 3 },
  { iata: 'CTU', city: 'Chengdu', country: 'China', region: 'asia', tier: 3 },
  { iata: 'TBS', city: 'Tbilisi', country: 'Georgia', region: 'asia', tier: 3 },
  { iata: 'MRU', city: 'Mauritius', country: 'Mauritius', region: 'africa', tier: 3 },
  { iata: 'SEZ', city: 'Seychelles', country: 'Seychelles', region: 'africa', tier: 3 },
  { iata: 'CMN', city: 'Casablanca', country: 'Morocco', region: 'africa', tier: 3 },
  { iata: 'CHC', city: 'Christchurch', country: 'New Zealand', region: 'oceania', tier: 3 },
  { iata: 'RAR', city: 'Rarotonga', country: 'Cook Islands', region: 'oceania', tier: 3 },
];
